[workspace]
members = ["src/firecracker", "src/jailer", "tools/pseudo_mm_template_creator"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[patch.crates-io]
vm-memory = { path = "vm-memory" }
